- xlgui/preferences/collection.py
When the translation is empty, gettext treats it as not translated, so it returns original value. So languages which keep the translation empty will get "the" here...
> Improve comment for translators

- po/hr.po
It would be useful to add a comment in xlgui/properties.py:1026 and :1028 to help translators understand and prevent these errors.
> Fix hr translation for python-brace-format

- xl/collection.py
I think it is not necessary to log compilation detection in normal mode since this is just informative for debugging purposes.
> Log compilation detection only in debug mode

- doc/dev/contributing.rst
Before reading the comment for #29 I didn't know that exailes translation is done on Weblate. This adds a URL so that users wanting to contribute to exaile by translating know what to do.
I know that this is no prominent position but at least it gets mentioned.
> Add URL to Weblate web site for translation

- xl/version.py
Currently if no git or git repository is found, an error message is printed to stderr of exaile. This is unnecessary and will be fixed by this commit.
> Ignore git error message

- plugins/moodbar/__init__.py
- plugins/previewdevice/__init__.py
As a precursor to changing these two plugins to work better together, this is a non-functional change to remove unused imports, fix indentation, etc. I used [yapf]https://github.com/google/yapf) on the moodbar plugin `__init__.py` because its indentation and white space were somewhat erratic.
> Reduce linter noise for previewdevice and moodar plugins

- .gitignore
- plugins/moodbar/__init__.py
- plugins/previewdevice/__init__.py
I like the info the moodbar gives me but I find I want it more from the preview device than the main player (because I'm previewing stuff live to decide what to play). This PR refactors the moodbar somewhat to abstract out the dependencies on the player and its gui, and then applies another instance to the preview device, when that is activated. To make this work I have added a couple of events to the preview device, and made it keep a reference to its progress bar which the moodbar plugin can see.
*    I have not changed the minor version numbers of either of the plugins. I guess you will want to do that, if you accept this, to reflect the fact that they have been modified.
> Make moodbar plugin work with preview device

- xlgui/menu.py
The main reason for removing the item is that the user has to be lucky
for clicking in the entry having a track selected.
Also, there is no other menu item depending on a track being selected.
The same functionality can be accessed by:
Right-Click on a track -> Properties
> menu: Remove 'Track Properties' item

- data/ui/collection_manager.ui
- data/ui/covermanager.ui
- data/ui/coverwindow.ui
- data/ui/device_manager.ui
- data/ui/preferences/preferences_dialog.ui
- data/ui/trackproperties_dialog.ui
With this change windows comply to the EWMH [1]. This reverts the previous change 04a0595. See #101 for details [3]
[1] http://standards.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472629520
[2] https://github.com/genodeftest/exaile/commit/04a059508ec182cc23e0b58eb7af2b6e26da1548
[3] https://github.com/exaile/exaile/pull/101#issuecomment-110265566
> Fix window type_hint property to "dialog"

- plugins/history/history_preferences.py
- plugins/previewdevice/previewprefs.py
- xlgui/preferences/__init__.py
GtkStock support was broken when porting to Gtk3.
This change makes the "history" and "preview device" plugins start.
> [gi] Drop GtkStock support for preferences pages

- plugins/bookmarks/__init__.py
- plugins/daapclient/__init__.py
- plugins/equalizer/__init__.py
- plugins/grouptagger/__init__.py
- plugins/grouptagger/gt_widgets.py
- plugins/history/__init__.py
- plugins/ipconsole/__init__.py
- plugins/lastfmlove/__init__.py
- xlgui/main.py
- xlgui/menu.py
- xlgui/panel/collection.py
- xlgui/panel/device.py
- xlgui/panel/menus.py
- xlgui/panel/radio.py
- xlgui/panels.py
- xlgui/playlist_container.py
- xlgui/preferences/collection.py
- xlgui/preferences/playback.py
- xlgui/preferences/widgets.py
- xlgui/properties.py
- xlgui/tray.py
- xlgui/widgets/dialogs.py
- xlgui/widgets/filter.py
- xlgui/widgets/info.py
- xlgui/widgets/menu.py
- xlgui/widgets/menuitems.py
- xlgui/widgets/notebook.py
- xlgui/widgets/playback.py
- xlgui/widgets/playlist.py
- xlgui/widgets/queue.py
This is the simple part of removing GtkStock. In most cases I could just use another icon exactly replacing the old one. Also changes the "Device manager" icon from 'harddisk' to 'multimedia-player'.
Added an image to "Covers".
What is left of GtkStock usage? Mostly dialog buttons plus some API in progress.py, icons.py, guiutil.py and some minor ones. I don't want to break API since I am not experienced in python programming.
> Remove GtkStock (the simple part)

- plugins/lyricwiki/__init__.py
Changed the url from http://lyrics.wikia.com/ to http://lyrics.wikia.com/wiki/ because there is a redirect from the first url to the second url anyway and new things take a while (multiple days) until the are available through the first url (but are available trough the second url immediately).
Note that there is also a bug in the lyrics viewer (the view with the actual text is not expanding, the lyrics cannot be seen).  A fix for that is not included because of https://github.com/exaile/exaile/pull/129 which also seems to addresses this.
It could also be fixed by changing 
```
<property name="expand">False</property>
```
To
```
<property name="expand">True</property>
```
in "plugins/lyricsviewer/lyricsviewer.ui" line 103
Thanks for your good work!
> Lyricwiki Plugin: Changed url to http://lyrics.wikia.com/wiki

- xl/metadata/__init__.py
- xl/metadata/ogg.py
Tags of opus files could not be read.
This small changes fix it (at least my manual tests where successful, but my python knowledge is limited, so please review thoroughly)
An example file could be found here:
http://xiph.org/~giles/2012/opus/detodos.opus
thx
> Fix: tags not read for opus files

- data/ui/panel/collection.ui
- xlgui/panel/collection.py
Use a GtkStack instead of adding and removing widgets
Center the "empty collection" message
TODO: change wiki entry for "empty collection" message after this PR is merged.
> Collection Panel: use GtkStack, center message

- README.OSX
Change GTK to GTK+ and OSX to OS X
> Fix spelling of GTK+ and OS X

- plugins/podcasts/__init__.py
Using `WARNING: ` in an INFO level log message is inconsistent. 
A better solution would be to distinguish 2 cases:
1. no podcast file exists. This is a valid use case and no problem. Don't `warn()` or `info()` but ignore.
2. podcast file exists but cannot be opened. In this case something is wrong, this is an invalid use case. `warn()` or `error()`.
> Don't write "WARNING" in an INFO level log message

- tests/xl/test_event.py
- xl/event.py
* Add add_ui_callback function to event to signify that you only want to receive events on the UI thread
* No more idle_add required, easier to audit
This is a first step towards fixing #83. I'd love feedback for making this more efficient, this was the first implementation that popped into my head. In particular, I wonder if there's a way that this could be implemented without using three separate dictionaries... I didn't want to keep checking to see if a callback was 'ui' or not, though, perhaps it's not that big of a deal. 
Fixed some correctness stuff in the weakref usage also.
@sjohannes , @genodeftest , thoughts?
Once this gets in, then I think the next step is to convert most of the UI classes to use add_ui_callback instead of add_callback... maybe plugins too. Then will need to …
> event: add first-class support for UI callbacks

- xlgui/properties.py
It looks like with a GtkStock icon this image always is 32x32 pixels.
I replaced it with a non-GtkStock icon, now the size is correct. As a side-effect the button has a slightly changed image.
> Tag Editor: fix "apply to all" button (size)

- data/ui/main.ui
- data/ui/panel/playlists.ui
- data/ui/widgets/progress.ui
- xlgui/__init__.py
- xlgui/main.py
- xlgui/progress.py
Move the ProgressManager into footer ("status bar") beside GtkStatusBar.
ProgressManager: Replace 2-line-design (grid) by one-line-design (box) to fit into footer
main window GtkPaned: force disable shrink of right and left child. Even after removing and re-adding left child. Note: this change effectively forces a minimum window size.
Playlists panel: force minimum size to match changes to main window GtkPaned.
> Main window: move ProgressManager into footer

- xl/playlist.py
Fix #37 RuntimeError: maximum recursion depth exceeded
Original reproducer lead to an infinite recursion in `__get_next()`
1. Create a new playlist
2. set shuffle mode to "shuffle tracks" and repeat mode to "repeat all"
3. Add one single song to the playlist
4. Press play
5. Press next
> repeat+shuffle: prevent recursion on playlist length of 1

- xl/main.py
This silences some warnings when starting exaile on recent (3.16+) Gtk versions.
> Add gi version requirements

- xlgui/panel/collection.py
- xlgui/widgets/common.py
This is reported as bug #156:
You couldn't right-click open a popup menu on multiple files or items. Exaile always deselected all but one elements.
Cause: handlers for signal button-press-event must return true in some cases. See [1] for this tip.
The change in DragTreeView reflects the fact that users might move their mouse a bit between pressing and releasing their right mouse button. In this case selection should not break either.
This issue would not have happened if python were enforcing explicit returns instead of assuming that returning nothing is returning False. Blame you, python!
[1] http://mailman.daa.com.au/cgi-bin/pipermail/pygtk/2005-June/010465.html
> Fix panel popup menu

- xl/plugins.py
In current development versions exaile would display an error message due to a folder named `__pycache__` in plugins dir. With this commit this folder will be ignored.
Tested from a git installation:
* list plugins
* enable, disable random plugins
__Edit:__ fixed markdown interpretion of underscores
> ignore __pycache__ dir when searching for plugins

- plugins/inhibitsuspend/__init__.py
Re-raise Errors to disable Plugin on failure …
> Don't make plugin seem to work if it doesn't.
Make session detection more robust …
> On gnome 3.18+Wayland, DESKTOP_SESSION defaults to 'gnome-wayland', this is fixed by this commit.
> XDG_CURRENT_SESSION is going to replace DESKTOP_SESSION, so add it to session detection.
> Since XDG_CURRENT_SESSION is not very old (see [1]) keep DESKTOP_SESSION.
> 
> A more elegant way to solve this would be using Gtk.Application.inhibit(), then we could get rid of most of this code.
> To do that Exaile would need to get ported to Gtk.Application first (much work included).
> 
> [1] https://askubuntu.com/questions/72549/how-to-determine-which-window-manager-is-running
I didn't test this plugin under KDE or xfce, just under gnome (both wayland and X11, …
> [gi] inhibitsuspend plugin: fix for wayland, make more robust

- xl/main.py
Prevent warning when opening preferences page "Plugins" for the first time. Since all the other essential `gi.require_version()` calls are here, I put it here too, which might be wrong.
> Require GIRepository

- data/ui/trackproperties_dialog.ui
- data/ui/trackproperties_dialog_cover_row.ui
- plugins/grouptagger/gt_widgets.py
- plugins/history/__init__.py
- plugins/librivox/__init__.py
- plugins/librivox/about_window.py
- plugins/minimode/controls.py
- plugins/previewdevice/__init__.py
- xlgui/main.py
- xlgui/playlist_container.py
- xlgui/progress.py
- xlgui/properties.py
- xlgui/widgets/dialogs.py
- xlgui/widgets/filter.py
- xlgui/widgets/info.py
- xlgui/widgets/notebook.py
- xlgui/widgets/rating.py
Replace Gtk{H,V}{Box,ButtonBox,Paned} with Gtk{Box,ButtonBox,Paned}.
Port track info dialog from GtkTable to GtkGrid.
Port some classes to GtkTemplate.
No major regressions expected.
> Some more Gtk+ 3.x work

- tests/xl/trax/test_search.py
- tests/xl/trax/test_track.py
- tests/xl/trax/test_util.py
mox3 is drop in replacement for pymox that is compatible with Python 3.
As pymox is not updated since 2010, I think it's reasonable to replace this.
> Migrate mox to mox3 for Python3 compatibility

- xl/playlist.py
It seems that `Gio.File.get_basename` does not replace spaces with `%20`. This causes errors when exporting playlists that have spaces in the name of the exported file. This simple change addresses that issue.
> Fixes exaile/exaile#253

- data/ui/widgets/.#tracklist_info.ui
- data/ui/widgets/tracklist_info.ui
- plugins/grouptagger/gt_widgets.py
- plugins/playlistanalyzer/analyzer.ui
- plugins/playlistanalyzer/analyzer_dialog.py
- xlgui/widgets/filter.py
I was looking to see if there were any remaining uses of the deprecated `Gtk.Table` and I found the following which I replaced with a `Gtk.Grid` instance. This should make any future transition to Gtk4 easier.
I had to rename some functions due to the name clash of 'Gtk.Grid.remove_rows()` with the some class methods.
> Remove deprecated Gtk.Table in plugins and replace with Gtk.Grid

- plugins/playlistanalyzer/__init__.py
When saving an HTML file from the Playlist Analyzer the following traceback occurs:
`Gio.File.replace() takes exactly 5 arguments (3 given)`
Apparently in `Gio.File.replace()` all the arguments are now required. This pull request simply supplies those arguments and passes the file content as a string so that the file can be written by`fp.write()`
> Fix Gio.File.replace() error when using Playlist Analyzer

- xlgui/widgets/menu.py
Fixes the random SEGVs caused by quickly jumping through application
menus (issue #97).
The crash is avoided by directly invoking self.clear_menu() when a
"hide" signal is emitted rather than delay it until the main loop is
idle.
This patch effectively undoes commit 040a5ca8 "Make GTK happy with
dynamic submenus"
> Fix #97: SEGVs in application menu

- tests/xl/trax/test_search.py
- xl/common.py
- xl/trax/search.py
- xl/trax/track.py
- xl/unicode.py
The problem this resolves is that mp4 returns BPM as an integer, not a string like the other formats. 
@sjohannes does this seem sane, or are there searches that I'm going to accidentally break by converting everything to a string? I'm not really sure if the `str(item)` conversion should be here... really, it seems like get_tag_search() should already be returning the correct thing? But if that's true, then we probably should move the unicode conversion over to get_tag_search also... 
Fixes a bug introduced by #261, #275
> Fix searching when non-string tags are present

- xlgui/widgets/dialogs.py
The dialog to export files from a playlist (launched with the 'Export
Files' context menu option over such playlist tab) fails because it
tries to assign a value to a free variable in a closure (which are
read-only in Python).
This patch modifies the logic in the closure so the free variable is
only used as an R-value.
> Fix Export Files playlist dialog (#299)

- xl/main.py
Postpone playing songs from either the command line or the restored
player state until the UI is loaded and operative. (Fixes: #302)
> Don't start playing songs until the UI is loaded

- xl/transcoder.py
According to the GStreamer documentation, module `vorbisenc`, `quality` ranges from −0.1 to +1.0.
Use setter functions to make sure the issue is not being made again.
> Fix vorbis default quality

- doc/conf.py
- doc/mocks.py
- exaile.py
- exaile_osx.py
- exaile_win.py
- tests/conftest.py
- tests/xl/player/gst/test_fader.py
- tests/xl/test_event.py
- tests/xl/trax/test_data.py
- tests/xl/trax/test_search.py
- tests/xl/trax/test_track.py
- tests/xl/trax/test_util.py
- tools/db_explorer.py
- tools/plugin_tool.py
Use pylint to clean up the exaile{,_osx,_win}.py and all python files in doc/, tests/ and tools/
Those changes are just cosmetic, but I intend to continue cleaning up all of exaile's code to ease reading code and finding bugs.
I'm doing this pull request now asking you whether you are interested in such work. It'll probably take a day or two where other commits are not welcome at the same time because rebasing is ugly.
> pylint: cleanup main, doc, tests, tools

- data/ui/panel/radio.ui
- data/ui/preferences/collection.ui
- data/ui/preferences/playback.ui
- data/ui/preferences/plugin.ui
- plugins/alarmclock/acprefs_pane.ui
- plugins/audioscrobbler/asprefs_pane.ui
- plugins/awn/awn_prefs_pane.ui
- plugins/bookmarks/bookmarks_pane.ui
- plugins/daapclient/daapclient_prefs.ui
- plugins/daapserver/daapserver_prefs.ui
- plugins/desktopcover/desktopcover_preferences.ui
- plugins/equalizer/equalizer.ui
- plugins/grouptagger/gt_import.ui
- plugins/history/history_preferences.ui
- plugins/ipconsole/ipconsole_prefs.ui
- plugins/minimode/minimode_preferences.ui
- plugins/multialarmclock/malrmclk.ui
- plugins/notify/notifyprefs_pane.ui
- plugins/notifyosd/notifyosdprefs_pane.ui
- plugins/osd/osd_preferences.ui
- plugins/previewdevice/previewprefs.ui
- plugins/replaygain/replaygainprefs_pane.ui
- plugins/screensaverpause/prefs.ui
- plugins/streamripper/streamripper.ui
xalign property is deprecated since Gtk+ 3.14.
Removing it has no side-effects in recent versions of Gtk+.
No side effects to be expected. This stuff was just hold back by Glade always re-adding the field on save [(see this GNOME bug)](https://bugzilla.gnome.org/show_bug.cgi?id=750985)
> remove deprecated xalign from builder XML files

- data/ui/coverchooser.ui
- plugins/previewdevice/__init__.py
- xlgui/cover.py
- xlgui/main.py
- xlgui/widgets/info.py
Replace or remove all remaining usages of Gtk.Alignment, which has been deprecated in Gtk+ 3.14.
> Replace deprecated Gtk.Alignment (fix warnings)

- xlgui/properties.py
Fixes a bug where the track properties window would become too wide for the
screen so user experience would suffer due to unreachable buttons.
Steps to reprodce the original bug:
1. have a file with comment containing some thousand characters in one line
2. open exaile's track properties dialog on it
What happens:
Dialog is very wide to fit the longest comment line without breaking it.
What should happen:
Either wrap the line (realized solution) or scroll horizontally (worse user experience because more user interaction needed for reading the text).
Additional info:
This solution has a downside: Shrinking the track properties dialog is very CPU intensive due to recalculation of text inside the GtkTextView.
> Cover window: Fix dialog being too wide

- plugins/moodbar/__init__.py
- plugins/moodbar/cache.py
- plugins/moodbar/generator.py
- plugins/moodbar/painter.py
- plugins/moodbar/widget.py
Cache:
* replaced URI-based filenames by hash-based filenames. This fixes #297.
* clean up some code
Generator:
* fixed a traceback occurring if the .mood file could not be created and thus the tmpfile does not exist
Painter:
* Fix array indexing on short tracks, make array indexing more flexible to any kind of track size
* MoodbarPainter: had just one function without usage of self, so removed this class
Widget:
* Fallout from Painter
Formatting:
* made sure that variables are initialized until `__init__()` finishes
* renamed some variables to not overlap with builtin symbols (format)
* renamed some variables to make the name more readable (e.g. `f` for file, `t` for thread)
* replaced old-style classes by new-style classes
I am ready to merge this. Comments?
> Plugin moodbar: rework cache filenames, cleanups and fixes

- xlgui/widgets/playback.py
I was able to confirm that the progressbar was causing periodic messages to be output under Orca. It no longer happens. I'm not 100% sure if this is the right fix, but it seems right... the documentation is fairly non-existent for Atk from what I can see.
> Playback: set Atk role for progressbar to AUDIO

- data/ui/splash.ui
This change should fix #342 or at least get around the warnings.
@virtuald : Can you please test under OS X, if this fixes #342?
> splash.ui: Splash screen is no popup window

- xlgui/preferences/widgets.py
- xlgui/widgets/info.py
During fixing the OSD plugin, I ran into a few issues I want to clear before committing the changes to the plugin itself. I'm still learning, so depending on your answers to my questions this pull request is not yet ready to merge.
> TrackInfoPane widget: Fix toggling progress bar visibility
No questions.
> preferences widgets: bugfix for TextViewPreference
Did this API change happen from 2.x to 3.x or within the 3.x series? Do we need to have version-specific code? If you know how to get this kind of information, please add a guide to the wiki.
> preferences widgets: Add new RGBAButtonPreference 
Should I store the value as `Gdk.RGBA` so it does not need to be parsed all the time? This will need a change in `xl.settings.TYPE_MAPPING`. Do want that?
There is only one other usage of …
> Some preparations to fix the OSD plugin

- doc/xlgui/icons.rst
- xlgui/icons.py
This function was broken ever since porting Exaile to Gtk+ 3.
It is not used anywhere, so we may just remove it.
This is part one of fixing #346.
> Remove unused broken function

- DEPS
- xl/main.py
- xl/player/gst/engine.py
- xl/player/gst/missing_plugin.py
This is a proposal for fixing #35, which is not yet ready to merge.
Assumptions:
* GstPbutils is always available. This might change requirements so that GStreamer plugins base is required by Exaile. This is relevant for distributions and packagers. I've added this to the spec file.
TODO, please help me on these issues / decisions:
* `__installer_finished_callback`: Should Exaile continue playback after successful installation? Should it bring its window to the front?
* ~~`__installer_finished_callback`: Should we handle any of the "failing" return codes?~~
* ~~`__handle_plugin_missing_message`: I have a "u" prefix in the message, how do I get rid of it?~~ solved.
* `__handle_plugin_missing_message`: This message looks bad (i.e. bad UI/UX), do you have any suggestions? Can we add an URL? …
> GStreamer Engine: Assist user on installing plugins

- xl/player/gst/engine.py
- xl/player/gst/sink.py
- xl/player/gst/sink_windows.py
@sjohannes what do you think... I can't think of a better way to inject this functionality. This seems to work on my Windows 7 VM. The only question I have is whether there should be a setting to enable/disable it... or maybe an exception handler in case it fails? But... it shouldn't really fail as far as I can see. Only available on Windows Vista and above, but I think GST requires Win7 anyways..
@dangmai you mentioned you were able to get stutter to happen on your machine at some point? Can you see if you can stimulate your machine to stutter with GST 1.x? I didn't have much luck with my machine. It would be interesting to know whether this branch makes a difference.
It's worth noting that for this to be even more effective, you really need a directsoundsink built with the patches in …
> gstreamer windows: Call AvSetMmThreadCharacteristics to boot thread priority

- xlgui/widgets/playback.py
`Gdk.Color` is deprecated in favor of `Gdk.RGBA`.
The drawing code already supports `Gdk.RGBA`, no more changes required.
> xlgui/widgets/playback.py: replace deprecated Gdk.Color

- plugins/ipconsole/__init__.py
- plugins/ipconsole/ipconsole_prefs.ui
- plugins/ipconsole/ipconsoleprefs.py
- plugins/ipconsole/ipython_view.py
- xlgui/guiutil.py
- xlgui/preferences/widgets.py
* ipthemes did not work, so they were removed
* disable opacity on Win32 because it could cause a segfault
* utilize the new RGBAButtonPreference instead of ColorButtonPreference
* get rid of the deprecated Gdk.Color
* `ipython_view.py`: replace deprecated `os.popen4()`
* improves compatibility with python 3 where `os.popen4()` has been removed
* code cleanup and imports resorted
* `__init__.py` is not being loaded from terminal
* it does not need an import hack
* add logging
* put preferences methods into plugin class
* utilize Gtk.StyleContext with CSS replacing deprecated methods from Gtk.Widget
* `modify_font()`, `modify_base()`, `modify_text()`
* this fixes coloring for font
* `xlgui/guiutil.py`: add function to convert font description from Pango to CSS
* utilize new css functions …
> plugins/ipconsole: fix colors, replace deprecated code, clean up

- .gitignore
- Makefile
- tools/generate-launcher
- tools/installer/_build.bat
- tools/installer/_build.sh
- tools/installer/_clean.sh
- tools/installer/project.config
- tools/installer/requirements.txt
Updated Exaile to use with the new `python-gtk3-gst-sdk`. The installer is created fine, however it is a bit large since it contains all the Gst plugins (~30mb out of the ~50mb generated installer). I'm not 100% sure which plugins we use, so I'll leave all of them in for now, but we can delete them before release if needed. Also, right now PyInstaller is pointing to my fork, we'll need to change that once they merge it in.
> Installer using MSYS2

- plugins/lyricsviewer/__init__.py
- plugins/lyricsviewer/lyricsviewer.ui
- plugins/lyricsviewer/lyricsviewer_prefs.ui
- plugins/lyricsviewer/lyricsviewerprefs.py
`lyricsviewer.ui`:
* Remove toplevel panel window
* toplevel box becomes a template
* utilize GtkStack to switch refresh_button child widgets
`lyricsviewer_prefs.ui`:
* Remove deprecated "use_action_appearance" property
* use font and size in GtkFontButton
`__init__.py`:
* clean up code, resort `import`s
* reflect changes in .ui file, including port to GtkTemplate
* create plugin class to utilize `on_gui_loaded()`
* remove unused function `modify_textview_look()`
* remove unused function `open_url()`
* integrate `update_source_text()` into `update_lyrics_text()`
* use GtkStyleContext with GtkCssProvider
* replaces deprecated method `Gtk.Widget.modify_font()`
* replaces deprecated method `Gtk.Widget.get_default_style()`
`lyricsviewer_prefs.py`:
* clean up code, resort `import`s
> plugins/lyricsviewer: remove deprecations, clean up

- xlgui/guiutil.py
Handle the case that pango_font_str can be None.
Fixes #375
> font css from pango font: Handle None argument

- plugins/daapserver/spydaap/cache.py
- plugins/daapserver/spydaap/containers.py
- plugins/daapserver/spydaap/metadata.py
- plugins/podcasts/__init__.py
hashlib.md5 was added in Python 2.5. We really don't need to support older python versions.
> Python: Remove pre-2.5 compatibility for MD5

- data/ui/preferences/appearance.ui
- xlgui/main.py
- xlgui/preferences/appearance.py
Bug fixes:
* Initialize with a sane value, otherwise `float(None)` will raise.
* As long as transparency is enabled, opacity must be less than 1.0, otherwise you'll have to expect artifacts
* Limit transparency so that users don't accidentially break their Exaile installation by fading it away
Improvement:
* Fix typo in preferences
* Remove deprecated widget properties
> Main window transparency: Fixes and improvement

- xl/common.py
- xlgui/widgets/playlist.py
- xlgui/widgets/playlist_columns.py
* Fix glib_wait to work correctly with instance methods (and now, only with instance methods)
* Fix playlist column width saving... seems like the button release callback it depended on wasn't always called, so use glib_wait instead to reduce the number of potential computations
One annoying side effect is that if you have multiple playlists showing, the other playlist will only update its position after a delay. But... I'm fine with that for now.
> Fix column width saving and glib_wait

- xlgui/widgets/playlist.py
The "activate" signal is emitted also when the GtkRadioMenuItem becomes unchecked, so the callbacks need to check the state of the widget before applying the mode.
Fixes #410.
> Playlist: on_{shuffle,repeat}_mode_set: apply mode only if widget is active

- data/ui/panel/collection.ui
- data/ui/panel/device.ui
- data/ui/panel/files.ui
- data/ui/panel/flatplaylist.ui
- data/ui/panel/playlists.ui
- data/ui/panel/radio.ui
- plugins/daapclient/__init__.py
- plugins/jamendo/__init__.py
- plugins/jamendo/ui/jamendo_panel.ui
- plugins/podcasts/__init__.py
- plugins/podcasts/podcasts.ui
- plugins/wikipedia/__init__.py
- plugins/wikipedia/data/wikipanel.ui
- xlgui/panel/__init__.py
- xlgui/panel/collection.py
- xlgui/panel/device.py
- xlgui/panel/files.py
- xlgui/panel/flatplaylist.py
- xlgui/panel/playlists.py
- xlgui/panel/radio.py
Commit message:
> Before this change, all panels are created with a parent window and are being reparented when loaded. This is unnecessary code.
> 
> This change introduces a simple way to allow panels being created without a window. All known panels have been ported to the new feature.
> 
> Also, some panels have been slightly redesigned, reducing the widget count.
This is part of #347.
> xlgui/panel: Allow panels without a parent window

- plugins/screensaverpause/PLUGININFO
- plugins/screensaverpause/__init__.py
The plugin currently only supports GNOME and KDE screensavers, but can support MATE and Cinnamon screensavers.
> Add support for MATE and Cinnamon screensavers to Pause on Screensaver plugin

- xl/playlist.py
Prior to this commit, when a playlist had "shuffle tracks" and "repeat all"
enabled, it would not play the last track any more after playing all tracks once.
Thanks to @sbrubes for the hint!
Fixes #247
Please check for unknown side-effects before merging.
> Fix shuffle playback missing last track in playlist

- xl/trax/track.py
Because `0` has been interpreted as `None`, sort order broke on numeric columns
Fixes #247.
> Fix #247: 0 gets sorted as the largest playcount value

- xl/trax/track.py
Because `0` has been interpreted as `None`, sort order broke on numeric columns
Fixes #287.
> Fix #287: 0 gets sorted as the largest playcount value

- .travis.yml
- Makefile
- doc/Makefile
Missing items:
Code style:
```
$ pycodestyle --exclude=plugins/daapserver/spydaap/*.py --max-line-length=160 --statistics --count --ignore=E203,E241,E265,E266,E305,E402,E722,E731,E741,W293,W503 .
```
Deferred:
> [WIP] Improve build: Makefile and more tests in Travis CI

- Makefile
This could have prevented a build error in debian stretch where the target "pot"
failed to make (#454).
I'll merge this as soon as it succeeds to build.
> Travis: Build everything

- xl/event.py
As far as I can tell, nothing uses this and it's just taking up extra space and causing extra computation that isn't useful.
> xl.event: Don't track event times, nothing uses it

- xl/trax/track.py
Note: This contains #457 , so only look at the last commit for this PR when reviewing it.
I'm less certain about this change... it does what is asked for by #357, but now that I'm thinking about it... should all notifications be suppressed when reading in a new file? Which means any reading done in `__new__` or `__init__` would not generate track_tags_changed notifications.
I'm fairly certain that suppressing them in `__init__` when url=something is desired behavior -- the only time `__init__` is going to be used with a URI object is to create a new track (otherwise `__new__` would return the old track). And if it's a brand new track, probably nobody cares about such notifications, right?
However, I think in `__new__`, the set_tags there should emit notifications, because the track will …
> Don't emit track_tags_changed when adding new files to the collection

- plugins/minimode/controls.py
- xlgui/widgets/playlist.py
- xlgui/widgets/playlist_columns.py
Since all the data we need is stored in the track object in the PlaylistModel, there's no reason to extract the information and store it in separate columns.    It turns out this is quite expensive. Instead, change the column renderers to    pull the text directly from the track, which has the added advantage of only
extracting data as needed, instead of rendering the entire playlist.
Contains other misc playlist fixes too.
> Massive speedup

- xlgui/widgets/playlist.py
Passing taget_list=None to Gtk.Widget.drag_dest_find_target, will make it use internally Gtk.Widget.drag_dest_get_target_list.
The bug is related to the lifetime of Gtk.TargetList returned by Gtk.Widget.drag_dest_get_target_list (When it gets destroyed, it crashes).
> Fix for issue #369 'Drag/drop crash on OSX'.

- xlgui/widgets/playlist.py
Workaround to internal Drag'n'Drop on OSX, use get_selected_tracks from source widget, if available
> Workaround to #479

- plugins/grouptagger/gt_widgets.py
This commit introduces line breaks which prevent the GroupTagger panel
to become too wide which would result in making all panels unreasonably
wide.
Fixes #489.
> GroupTagger: Force line break in title/artist labels

- xlgui/guiutil.py
- xlgui/widgets/playlist.py
Previously, when filtering it would just scroll to the top... which is fairly annoying if you're dealing with a large playlist.
This PR restores the normal behavior if you were just using a normal treeview + model without removing the model.
Also includes a fix to #485, as that fix can use the without_model helper function that was introduced here.
> playlist: restore view when filtering

- plugins/keybinder/__init__.py
- plugins/notify/__init__.py
It seems not all plugins have been updated to have their teardown() method include the second argument. 
This causes the following errors being displayed on terminal when shutting down the program:
```
...
INFO    : Exaile is shutting down...
INFO    : Tearing down plugins...
ERROR   : Unable to tear down plugin notify
Traceback (most recent call last):
File "/home/rok/Projects/exaile/xl/plugins.py", line 296, in teardown
plugin.teardown(main)
TypeError: teardown() takes exactly 1 argument (2 given)
ERROR   : Unable to tear down plugin keybinder
Traceback (most recent call last):
File "/home/rok/Projects/exaile/xl/plugins.py", line 296, in teardown
plugin.teardown(main)
TypeError: teardown() takes exactly 1 argument (2 given)
INFO    : Saving state...
INFO    : Bye!
```
This PR fixes the …
> Fix plugins' teardown() method signature

- plugins/notify/__init__.py
As noted by @sbrubes, in my previous PR I overlooked the underscore in the name of second argument  in the disable() method.
> Fix the argument name in notify plugin's disable() method

- xl/covers.py
- xl/main.py
- xl/migrations/database/covers_1to2.py
See #306 for the motivation for this patch.
One of the exciting changes here is that it adds support for the `musicbrainz_albumid` tag. When this tag is available, we don't need to check anything else; it uniquely identifies the album.
This patch also incorporates @sbrubes's idea to use the `date` tag, because [one artist can release multiple albums with the same name](https://forums.macrumors.com/threads/itunes-two-albums-with-same-name-and-album-artist.1505017/).
So the possible track keys are, in order of preference (`[]` means the tag will be used iff it's available):
* musicbrainz_albumid
* album albumartist [date]
* __compilation [date]  # __compilation is a (directory, album) tuple
* album [artist] [date]
I've also changed the format of the output of this function. The function can …
> Covers: Support multiple albums having the same name

- plugins/mpris2/mprisobject.py
This PR improves the conformity to MPRIS2 specification:
- PlayPause now starts the playback if it is stopped (instead of just toggling pause) - ```If playback is stopped, starts playback.```
- Next and Previous have effect only if player is in playing state - ```If playback is paused or stopped, it remains that way.```
> MPRIS plugin: improve conformity to spec

- plugins/keybinder/__init__.py
Just toggling pause does not start the playback for the stopped state, so we now explicitly start it.
> keybinder plugin: on XF86AudioPlay, start playback if it is stopped

- plugins/daapclient/spydaap/daap.py
- plugins/daapserver/spydaap/daap.py
When retrieving the atom value with DAAPObject.getAtom(), None will
be incorrectly returned when the code corresponds to a child
atom with integer value 0.
This is because the validity of the returned value is checked via
boolean coercion instead of explicitly checking for None (and thus
0 evaluates to False, same as a None would have).
Fixes issue #447.
> DAAP plugins: fix the retrieval of atoms with integer value 0

- data/ui/preferences/appearance.ui
- xlgui/main.py
- xlgui/preferences/appearance.py
Tried this on Windows 7... it doesn't look that terrible. I suspect it would look better on Windows 10 if you were using a dark Windows theme already, but I don't have such a system available to me.
On Linux it doesn't seem that I can specify the non-dark theme anymore... and when I pick a theme that doesn't have a corresponding dark theme, this doesn't seem to do anything.
> Add option to use a 'dark theme' if available

- plugins/daapclient/__init__.py
Otherwise, it will be stored to the list of opened panels as
dbus.String() type, causing the following error:
NameError: name 'dbus' is not defined
when restoring the GUI on the next program start.
> daapclient: explicitly convert panel's name to string

- xl/player/gst/gst_utils.py
This PR addresses an issue with displaying properties of a track from a DAAP share. When a track is added to a playlist, it is possible to show its properties by right clicking on it and selecting "Track properties". But, once the track has been played, the same action results in the following error:
```
Traceback (most recent call last):
File "/usr/share/exaile/xlgui/widgets/playlist.py", line 361, in <lambda>
'document-properties', lambda w, n, o, c: o.show_properties_dialog()))
File "/usr/share/exaile/xlgui/widgets/playlist.py", line 1508, in show_properties_dialog
current_position, with_extras)
File "/usr/share/exaile/xlgui/properties.py", line 130, in __init__
self.trackdata = self._tags_copy(tracks)
File "/usr/share/exaile/xlgui/properties.py", line 191, in _tags_copy
if …
```
> Improve parsing of tags from remote streams

- plugins/equalizer/__init__.py
As reported by @sjohannes, apparently the eq window was blank after you closed it the first time. This PR fixes that.
> Equalizer: recreate the window when it gets destroyed

- tools/installer/exaile.spec
Haven't tested this (I don't have the setup to build the installer), hopefully it's correct.
Fixes https://github.com/exaile/exaile/issues/532
Fixes https://github.com/exaile/exaile/issues/534
Fixes https://github.com/exaile/exaile/issues/538
> Exclude WASAPI plugin from installer

- plugins/daapclient/__init__.py
- plugins/daapclient/client.py
- xl/player/gst/gst_utils.py
This PR improves the metadata retrieval for tracks in remote locations, with the main aim of enhancing the collection views for remote (DAAP) shares.
The first commit adds parsing of track year/date from the remote stream's metadata when the track is played. Like all metadata set at the playback time, this information serves as a fall-back for the case when it is not retrieved otherwise (e.g., at the moment, daapclient plugin does not retrieve track year).
The second commit modifies daapclient plugin to parse track year (which is already in the list of retrieved DAAP atoms), with the goal of enabling "Date - Artist", "Date - Album", and "Artist - (Date - Album)" views in collection pane.
The third commit similarly adds retrieval of disc number, which improves track sorting within …
> Improve metadata retrieval for remote tracks (DAAP)

- xlgui/widgets/playback.py
- Fixes #544
Tested on OSX and this does the trick. We should probably clean house at some point with the various gsignal things we have, but this is fine for now I think?
> playback: remove draw override for compat with pygobject 3.30

- xl/metadata/__init__.py
Direct instantiation of BaseClass will set '_reverse_mapping' field
in the BaseClass, and thus prevent format-specific initialization
of '_reverse_mapping' for child classes that may get instantiated
afterwards.
Instead, use a DummyFormat class. Fixes issue #539.
> Metadata: avoid directly instantiating BaseClass for unsupported formats

- plugins/playlistanalyzer/analyzer_dialog.py
All the other settings use "playlistanalyzer" (as is the plugin name) while this one used "playlist_analyzer". This bothers my sensibilities.
For reference, the setting stores the last save location so the user doesn't have to re-choose it each time they run the analyzer. This commit loses the existing value and leaves the incorrect entry in `settings.ini`, but actual user impact should be negligible.
> playlistanalyzer: Fix wrong setting name

- doc/dev/getting_started.rst
Without it, exaile appears to be mysteriously stuck after "Mutagen works" message, because we get an exception that does not seem to be displayed on stdout (flushing issue?)...
> docs: add mingw-w64-i686-python2-bsddb3 to list of Windows dependencies

- xl/common.py
Unicode strings need to be converted to byte strings before
they are passed to underlying stream.write().
Fixes #560.
> common: GioFileOutputStream: handle unicode strings in write()

- xlgui/__init__.py
- xlgui/widgets/dialogs.py
For when we get theme-specific bugs.
> Show GTK+ theme name in About dialog

- xlgui/widgets/rating.py
This PR should address #551, which is caused by click_area being effectively (0, 0, 0, 0) due to its members not being initialized from the values passed the constructor. The second commit allows user to set the rating even if clicked above or below the stars in the corresponding cell.
> Playlist rating fix

- xlgui/widgets/filter.py
When running localized version of Exaile, the combo boxes in
SpinDateField (e.g., for "Last played") keep resetting to seconds
every time the dialog is re-run.
The issue is that set_state() translates the input unit string
before trying to look it up in internal list of (non-translated)
strings.
> widgets: SpinButtonAndComboField: fix state restore in non-C locale

- xl/playlist.py
Due to incorrect comparison of "timestamp" string against _TD object
returned by tag_data.get(field), we failed to detect timestamp-based
fields, which in turn broke the search/filtering. The comparison
should be done against "type" member of the _TD object.
Should fix #19 (which was reopened for 4.0.0).
> Playlist: _search_playlist: fixed detection of timestamp-based fields

- xlgui/widgets/playlist_columns.py
In certain scenarios (e.g., during menu (re)population), we may
receive an "activate" event for a radio menu item that is not
active anymore. Therefore, on_sizing_item_activate() needs to
verify the menu_item's actual state before taking action.
Fixes #586, where such spurious activation is emitted for the
first radio item ("Resizable"), and thus we always end up marking
it as selected.
> Playlist columns: filter out activation events for non-active size items

- xl/common.py
- xlgui/widgets/playlist_columns.py
We need to call `get_width` directly in the `notify::width` signal handler. We can't call it inside a `common.glib_wait`ed function because the width may be wrong there.
This merge request also includes documentation change to `common.glib_wait`. Previously, if there are multiple calls batched into one, the set of arguments being used is undefined. Now we specify that the last set always wins (the code already does this but it was considered implementation detail).
Fixes #580
> Fix columns being shrunk to 0 size on older GTK+

- appveyor.yml
I think we are OK about #584.
Things to do **before** accepting this PR (in this order):
This `appveyor.yml` file builds and deploys Exaile Windows installer to each new tag.
> Add AppVeyor file to build Windows installer

- tools/installer/exaile_installer.nsi
Before this path: 48.9MB (installer) / 163MB (installed)
After this patch: 45.1MB (installer) / 150 MB (installed)
I don't see any troubles without fonts directory.
> Windows installer: Don't package fonts

- xl/version.py
Related to #588.
> Maybe we should just check for the .git directory.
So that's what I did.
> Get current git revision only if .git directory exists

- plugins/cd/PLUGININFO
- plugins/cd/__init__.py
- xl/hal.py
- xl/main.py
HAL has been deprecated for years and has been removed from most Linux distributions . Even its successor, UDisks version 1 has been superseded by UDisks2 about 4 years ago.
FreeBSD has its own implementation of UDisks2: https://svnweb.freebsd.org/ports/head/sysutils/bsdisks/
@rokm: Do I remember correctly that you are using FreeBSD? If yes, can you please check whether this works for you too?
The massstorage plugin is still broken, see #610 for that.
> Drop hal and UDisks(1) support

- xlgui/accelerators.py
- xlgui/guiutil.py
This PR is an attempt to address #568. The issue is that the accelerators installed to main window are triggered even when editing a text entry. As far as I am aware, the only way around this is to temporarily remove the accelerators when text entry gains keyboard focus, and reinstall them once the focus is lost.
To do so, the first commit extends AcceleratorManager with two new methods that allow enabling/disabling all registered accelerators (in addition to keeping track of registered/unregistered providers/accelerators).
The second commit adds support for disabling and re-enabling accelerators when guiutil.SearchEntry gains and loses keyboard focus, respectively. This allows skipping between the words with ctrl+arrow not only in Playlist's Search entry (#568), but also in all other …
> Temporarily disable main window's accelerators in search entry widgets

- xl/formatter.py
- xlgui/widgets/playlist.py
- xlgui/widgets/playlist_columns.py
This PR implements editable comment playlist column (enhancement #579).
The first commit makes ```CommentTagFormatter``` use ```get_tag_raw()``` instead of ```get_tag_disk()``` to retrieve the comment. Without this change, the comment column always displays the comment stored in the music file, and fails to reflect the changes made to the comment via Exaile's Track properties dialog.
The second commit addresses interference with selection of an editable column, which turns out to be caused by code-path that aims to preserve multiple-item selection for DnD. Since the latter is relevant only for multiple-item selection, it should be activated only when multiple items are actually selected.
The third commit marks the comment column as editable and implements storage of the edited value.
The …
> Editable comment playlist column

- plugins/lastfmlove/cellrenderertoggleimage.py
- tools/.bpythonrc
- tools/ipcli
- tools/ipshell
I'm packaging Exaile 4.0.0.rc4 for Arch Linux, and I see `namcap` complains about the built package:
```
$ namcap exaile-4.0.0.rc4-1-any.pkg.tar.xz
exaile E: Dependency python detected and not included (programs ['python'] needed in scripts ['usr/share/exaile/plugins/lastfmlove/cellrenderertoggleimage.py'])
```
It is because `namcap` thinks Python 3 is required (due to Arch's default), but it is not the case.
I prefer to set an explicit Python version to avoid this.
> Explicit python2 in all shebangs

- README.md
Potential users often expect all the info about a project in the GitHub readme. We're not doing this, but we should at least point them to our website, which has more info (e.g. screenshots).
> README: Point to exaile.org instead of readthedocs

- xl/plugins.py
On our official Windows builds, some of the plugins are mistakenly marked as potentially broken (⚠️). This is because the RequiredModules field in PLUGININFO files are checked using `imp.find_module`, which doesn't work with whatever magic PyInstaller uses to package modules. This changes the check to use `pkgutil.find_loader` instead, which works correctly for this.
Fixes: https://github.com/exaile/exaile/issues/629
> plugins: Use pkgutil.find_loader when checking is_potentially_broken.

- xlgui/widgets/playlist.py
Original comment was:
>  Grab focus upon click in playlist views (fixes a bug where opening the track properties dialog fails to open due to wrong selection)
I can't seem to duplicate that condition, and I know we've fixed a lot of things related to playlists and selection since then, so I'm guessing it's not needed anymore.
Related to #633
> playlist widget: don't always grab focus in button_press_event

- xlgui/main.py
I don't think the key definitions (e.g. `<Primary>F`) are meant to be translated here. Anyway the `_(keys)` call is definitely wrong because the keys themselves are not currently marked for translation.
> Fix wrong gettext call on shortcut keys

- xl/trax/track.py
- xlgui/widgets/playlist_columns.py
Requires updating the `Track.set_tags*` API
> editable columns: Only save changes to disk if changes have been made

- appveyor.yml
- tools/installer/project.config
Currently the installer breaks if the build host's MSYS runtime is newer than the SDK's.
> Installer: Fix crash when running executables in SDK if MSYS has been updated locally

- xlgui/playlist_container.py
- xlgui/widgets/notebook.py
A fix for issues with non-ASCII characters in playlist name (#643 ).
The original issue is caused by the decode() call on page name, which is already a unicode object. 
(Unless I am mistaken, the decode() call would make sense if the name was a str object containing UTF-8 characters. To get from unicode back to str, encode() should be used instead. But since default_playlist_name and consequently default_name_parts are also unicode objects, no conversion is actually required).
The second issue (error upon closing exaile) is fixed by ensuring that the name which we pass to encode_filename is a unicode object instead of str.
> Fix unicode handling in playlist names

- xl/logger_setup.py
See Python's documentation on [String Formatting Operations](https://docs.python.org/2.7/library/stdtypes.html?highlight=sprintf#string-formatting-operations).
> xl/logger_setup.py: Add leading zeros to milliseconds

- xl/main.py
This is necessary to change the app_id under Plasma wayland
session from default 'exaile.py' to 'exaile', which in turn
allows matching with the exaile.desktop file. Fixes #653.
> Use GLib.set_prgname() to set program name to 'exaile'

- xl/devices.py
Prior to this commit, you would see a warning about object() taking no arguments because Device() was invoked with too many arguments.
> xl/devices.py: Fix warning

- .travis.yml
cf.
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
modified:   .travis.yml
> Remove deprecated keyword "sudo" from travis config.

- .travis.yml
Our code *should* also compile with the latest ubuntu LTS which is 18.04 and has python 3.6.
> Travis: Enable CI on ubuntu 18.04 LTS

- plugins/massstorage/__init__.py
- xl/playlist.py
This PR is based on py3 branch and testing with Python 3.8:
- Python3 SyntaxWarning fix: is not "" (use !=)
- cgi.parse_qs deprecated in python3 and removed in python3.8; use urllib.parse
> [py3] SyntaxWarning and removed API fixes

- plugins/massstorage/__init__.py
#673 broke the CI format-check. Let's unbreak it.
> py3: Fix code formatting after #673

- .travis.yml
- doc/mocks.py
This fixes #667  for me on Fedora 31 with python 3.7.6.
However, I am not really familiar enough with this area of python to be certain that there are no side effects.
This seems to be the relevant reference: https://www.python.org/dev/peps/pep-0560/
> py3: fix documentation generation on python 3.7+

- doc/mocks.py
Second attempt at fixing the documentation generation issue, tested both with python 3.6.x on Ubuntu 18.04 and 3.7.x on Fedora 31.
This time, the ```__mro_entries__``` issue is addressed by raising the ```AttributeError```.
However, this still leaves the ```TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases``` error, which is caused by the mocked ```GObject.GObject``` being involved in multiple inheritance in ```xl.common.ProgressThread```. For this to work, we need our ```Mock``` object for the ```GObject``` module return a type instead of an instance for ```GObject``` (class).
Due to the name repetition (```gi.repository.GObject.GObject```, with ```GObject``` referring both to the module and the class) and …
> py3: fix documentation generation on python 3.6+ (try 2)

- plugins/daapclient/__init__.py
- plugins/inhibitsuspend/__init__.py
- xlgui/preferences/collection.py
```
/home/travis/devel/exaile/xlgui/preferences/collection.py:37:
SyntaxWarning: "is not" with a literal. Did you mean "!="?
return [v.lower() for v in default_strip_list.split(' ') if v is not '']
/home/travis/devel/exaile/xlgui/preferences/collection.py:54:
SyntaxWarning: "is not" with a literal. Did you mean "!="?
values = [v.lower() for v in self.widget.get_text().split(' ') if v is not '']
```
> [py3] Fix SyntaxWarnings

- plugins/daapclient/__init__.py
- plugins/daapserver/server.py
- plugins/osd/__init__.py
- plugins/podcasts/__init__.py
- xl/migrations/database/to_bsddb.py
- xl/player/gst/engine.py
- xl/player/gst/missing_plugin.py
- xlgui/__init__.py
- xlgui/panels.py
logging.warning() is just the same without deprecation notice.
Note: `logging.warn()` is not only deprecated since python 3.3 but has never been documented ([Details](https://bugs.python.org/issue13235)).
> Python: Replace calls to deprecated logging.warn()

- xl/main.py
- xl/trax/track.py
- xl/trax/trackdb.py
* xl/main.py: These changes are hard to find, but they are deprecated for almost 10 years now so I think it is ok to remove them.
* xl/trax/{track,trackdb}.py: I could not find any code in our repo using these deprecated functions, so I removed them.
> [Py3] Remove a few deprecated functions

- xl/metadata/mod.py
Changes:
* bump libmodplug soname version to match fedora31, debian8+, ubuntu12.10+
* mention in DEPS that you need to install libmodplug for modplug
metadata
* add logging to give a hint if metadata fetching does not work for the
MOD file format
> Mod format: bump soname version, mention in DEPS, add logging

- plugins/daapclient/__init__.py
Fedora 32 dropped python3-avahi, so this might be a good opportunity to enable DAAP share discovery via python-zeroconf.
The PR contains fixes for some subtle menu-management issues in the existing Avahi backend, an addition of a zeroconf-based backend, and a subsequent extension to accomodate older python-zeroconf versions. As #517 indicates that we may want to drop the Avahi backend altogether, no attempt has been made to consolidate the shared/duplicated code between both backends.
Tested with python-zeroconf v.0.25.1 on Fedora 32, and with v.0.17.6 and v.0.21.3 on Debian Buster.
Fixes #517.
> daapclient: python-zeroconf support

- tools/installer/exaile.spec
Required for launching external programs from GLib/Gtk applications.
Fixes #712.
> installer: make sure to bundle gspawn-*helper.exe on Windows

- xl/trax/track.py
If tracks are added to the cacher fast enough, multiple entries can have
the same time (i[2]). This then causes the min((i[2], i) ...) call to end
up comparing the track objects (i[0]), causing a spurious error preventing
the Track Properties dialog from opening:
TypeError: '<' not supported between instances of 'Track' and 'Track'
After this change, the code will pick any arbitrary item with the lowest
time value.
> track._MetadataCacher: Fix error when the time is the same

- data/ui/collection_manager.ui
- xlgui/collection.py
Display unescaped location URIs instead of original, escaped ones. Fixes #722.
> xlgui: collection manager dialog: display unescaped location URIs

- xlgui/collection.py
The collection manager dialog disallows addition of locations that are subdirectories of locations already existing in collection,
but does not disallow addition of location that is the same as a location that already exists in collection.
This is because a Gio.File is not a prefix of itself, so we also need to check for equality using Gio.File.equal().
> xlgui: collection manager dialog: disallow addition of duplicated locations

- plugins/mainmenubutton/__init__.py
- plugins/minimode/controls.py
- xl/migrations/database/__init__.py
- xl/trax/track.py
- xlgui/widgets/common.py
- xlgui/widgets/dialogs.py
- xlgui/widgets/info.py
- xlgui/widgets/notebook.py
- xlgui/widgets/playlist.py
Python:
* imp: Obsoleted by importlib, but let's just use normal import.
GTK:
* Entry.set_inner_border: We're supposed to use CSS, but things look fine
on Adwaita so we'll do without it for now.
* TreeView.set_rules_hint: No replacement, seems to already do nothing.
* Widget.drag_source_set_icon_stock: Use ..._set_icon_name.
* Image.set_from_stock: Use set_from_icon_name.
* Widget.reparent: Use remove+add.
GIO:
* FileInfo.get_modification_time: Use get_modification_date_time.
PyGObject:
* Gtk.Widget.stop_emission: Use stop_emission_by_name,
* Gtk.MessageDialog constructor args: Use GObject property construction.
> Fix some Python, GTK, GIO, PyGObject deprecations

- Makefile
This prevents having the tests use / rely on translated strings.
Fixes: https://github.com/exaile/exaile/issues/735
> Set LC_ALL=C on `make test`

- tools/plugin_tool.py
- xl/version.py
- xl/xdg.py
Allows `plugin_tool.py` to import `xl.xdg`, which enables creation of distribution tarball in an environment that does not have `PyGObject` installed.
> Allow tools/plugin_tool.py run without PyGObject/GLib

- xl/trax/util.py
In Exaile core this is always called with a URI so it works, but the tests
call it with a local file path and we get test failures. (It must have
worked in earlier GIO versions, because our CI doesn't catch this.)
trax.Track uses new_for_commandline_arg for its location argument, so this
should be correct.
Fixes: https://github.com/exaile/exaile/issues/750
> trax/util.is_valid_track: Change new_for_uri to new_for_commandline_arg

- plugins/lyricsmania/__init__.py
- plugins/somafm/__init__.py
A couple of plugins are using the wrong address for the FSF in their license text
> Use the correct address for the FSF

- plugins/bpm/bpmdetect.py
- plugins/ipconsole/ipython_view.py
These plugins are installed through the Makefile without execute permissions and so have redundant shebangs at the top of the file.  The shebangs may be useful during development but in that case the developer can explicitly call python to run the file anyway.
> Remove shebangs from plugins installed without execute perms

- Makefile
Modifies the install command used in the Makefile to add a flag to preserve the timestamps from the released files.  This is a 
Fedora packaging guideline, see https://docs.fedoraproject.org/en-US/packaging-guidelines/#_timestamps
> Preserve timestamp upon file installation.

- xl/collection.py
Attempt to mitigate errors that arise when files in monitored collection are removed shortly after being created (#764).
> xl/collection: mitigate errors when files are removed during scan

- xl/trax/track.py
Hello Johannes,
this problem happens in case that there is a track with none rating.
In the case the get_tag_sort function returns None.
Instead the track function get_rating should be used, shouldn't it?
> Bugfix Unable to sort a playlist with rating value #758

- .github/workflows/ci.yml
Fedora 33 is EOL, see the Fedora 35 schedule:
https://fedorapeople.org/groups/schedule/f-35/f-35-key-tasks.html
> CI: Update to testing with Fedora 34

- tests/conftest.py
`pytest.yield_fixture` is is a deprecated alias for `pytest.fixture`.
Documentation: https://docs.pytest.org/en/6.2.x/deprecations.html?highlight=yield#the-yield-fixture-function-decorator
> Tests: Get rid of pytest warnings

- DEPS
- tests/xl/trax/test_search.py
- tests/xl/trax/test_util.py
- Fixes #817
Note that the tests in test_util.py still use mox, but... they're all skipped because I never fixed them previously, so I guess it's ok to keep them skipped? Not 100% sure what the tests were supposed to do.
> tests: remove mox3 dependency

- Makefile
Without doing this I get:
ImportError while loading conftest '/path/to/exaile/tests/conftest.py'.
tests/conftest.py:7: in <module>
from gi.repository import Gio
E   ModuleNotFoundError: No module named 'gi'
> makefile: append directory to existing PYTHONPATH

- xl/common.py
See https://github.com/exaile/exaile/issues/770 for context.
I've barely tested this, so would love to get feedback from people who have berkeleydb installed but not bsddb3.
> Try import berkeleydb if bsddb3 fails

- xl/player/gst/engine.py
- xl/player/player.py
- xl/playlist.py
- xlgui/widgets/playlist.py
This branch is based on #820.
<s>With these changes the behavior is as I would expect, except the play/pause button gets left with the pause symbol showing when it is in a stopped state and the button actually behaves as a play button.</s> (fixed)
I do not believe there is any way to accomplish proper SPAT behavior
from within the playlist/queue, so we need to add the ability to
propagate a command to stop up to the engine.
> SPAT: leave next track ready to play. Fix #767.

- xl/main.py
- xl/player/queue.py
- xlgui/__init__.py
I have the option resume_playback enabled and use queue and playlist
If I play a track in the playlist and close Exaile, after a restart the track in the playlist is neither selected nor played.
Instead the last selected track in queue is played.
> Select correct playlist and track if starting with option resume_playback and gui

- data/images/scalable/exaile-noshadow.svg
- data/images/scalable/exaile-pause.svg
- data/images/scalable/exaile-play.svg
- data/images/scalable/exaile.svg
To be compatible with Debian Free Software Guidelines CC-BY-2.0 needs to be upgraded to CC-BY-4.0
See https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution-ShareAlike_3.0_Unported_.28CC_BY-SA_3.0.29
@mathbr Do you agree?
> Upgrade Licensing to CC-BY-4.0 to be compatible with Debian FSG

- xl/trax/search.py
~When processing the tracks in `search_tracks` generator, yield the current thread's timeslice only when running in the secondary (non-main) thread. This prevents unnecessary slow-downs in the main thread, where we want to finish the operation as fast as possible (especially under python 3.11 on linux, where `time.sleep(0)` introduced additional overhead).~
When processing the tracks in `search_tracks` generator, do not explicitly yield the current thread's time-slice via `time.sleep(0)`.
Removal of sleep call prevents unnecessary slow-downs in the main thread, where we want to finish the operation as fast as possible (especially under python 3.11 on linux, where `time.sleep(0)` introduced additional overhead).
The comment accompanying the sleep call refers to GIL behavior, which might …
> xl/trax: search_tracks: remove time.sleep(0)

- plugins/winmmkeys/PLUGININFO
- plugins/winmmkeys/__init__.py
- tools/installer/requirements.txt
[`pynput`](https://github.com/moses-palmer/pynput) seems to be way to go for multimedia keys support on Windows, now that `keyboard` doesn't work anymore (see <https://github.com/exaile/exaile/issues/830>).
I suppose pyHook might still work, but I haven't tested it in a long time. Being an extension module, pyHook is more annoying to deal with compared to pynput (which uses ctypes), so let's just settle on pynput.
I haven't tested this with the installer; was hoping to test using a CI build, but apparently this needs a new SDK build (due to requirements.txt change), which in turn requires this to be merged to master first.
> winmmkeys: Use pynput; remove support for other modules

- DEPS
- xlgui/widgets/info.py
The `typing` package from python 3.7 stdlib does not provide `Literal` type, so external `typing-extensions` package must be used instead.
Alternatively, we should drop official support for python <= 3.7.
> Fix python 3.7 compatibility

- xlgui/preferences/__init__.py
- xlgui/preferences/widgets.py
Old behavior in case the AudioSink is set to automatic:
* Open settings
* Go to Playback settings, only AudioSink and AudioSinkDevice are show on top, CustomSinkPipe is hidden
* Go to Collections settings
* Come back to Playback settings
=> Resulted in showing the preferences AudioSink, AudioSinkDevice and CustomSinkPipe
Now only  AudioSink and AudioSinkDevice are shown as expected.
> Check conditional preferences conditions on show

- exaile_win.py
Recent versions of PyInstaller do not provide dummy `sys.stderr` and `sys.stdout` in noconsole/windowed mode anymore. Instead, they are left at `None`, same as when script is ran using `pythonw.exe`.
Provide dummy file-like objects for `sys.stderr` and `sys.stdout` to prevent errors in parts of the code that blindly assume that the streams are available.
> Windows launcher: provide dummy sys.stderr and sys.stdout

- xl/metadata/_base.py
- xl/metadata/_id3.py
- xl/metadata/flac.py
- xl/metadata/ogg.py
- xl/trax/track.py
* Tags sometimes are not written to file metadata if "write_rating_to_audio_file_metadata" is active
* If tags are writable, rating was always written, regardless of write_rating_to_audio_file_metadata
Tested with properties and bpm plugin.
I.e. tried to store bpm to flac file either with "write_rating_to_audio_file_metadata" active or not
> Bugfix: Tag writing with "write_rating_to_audio_file_metadata"

- plugins/icecast/__init__.py
> Icecast: Encoding must be set to save xml data properly on Windows

- tools/installer/exaile.spec
In GStreamer 1.22.1 used by our SDK 39, the `soup` GStreamer plugin, which is used for radio streams, is not linked against the `soup` shared library (DLL) anymore, so PyInstaller fails to pick up the DLL and some of its dependencies. Failing to load the `soup` plugin causes fall-back to `curl` one, which seems to fail to load any radio stream.
Therefore, ensure that `libsoup-2.4-1.dll` is collected, by passing it to PyInstaller via `binaries` in the spec file.
Fixes #867.
> win installer: manually collect libsoup-2.4-1.dll and its dependencies

- xl/metadata/__init__.py
- xl/metadata/aac.py
According to https://mutagen.readthedocs.io/en/latest/api/aac.html ID3 tags can be used with aac.
Checked with kid3.
> Add metadata handler for aac files

- plugins/cd/__init__.py
The cd-plugin loads the parser modules for discid and musicbrainzng dynamically to catch missing dependencies.
This works in case Exaile is run from source and plugins are in `{$exaile_dir}/plugins` because the `$exaile_dir` is in sys.path
If Exaile is installed to the system the exaile directory is /usr/lib/exaile and plugins are in /usr/share/exaile.
In this case the plugins directory is not in sys.path
> Add plugin path to sys.path to allow dynamic loading of modules

- plugins/cd/__init__.py
- plugins/cd/_cdguipanel.py
- xl/transcoder.py
Some small fixes:
* Missing gettext
* Retrieving default format from formats list
* encode as mp3 needs to use lamemp3enc now
FWIW reading the disc index (https://github.com/exaile/exaile/blob/master/plugins/cd/__init__.py#L174) is seems not to be running on its own thread.
At least here Exaile gui is blocked during reading the index.
@ryneeverett Do you know of this?
> Small trifles with cd plugin

- data/ui/preferences/collection.ui
- xl/main.py
- xl/metadata/flac.py
- xl/metadata/ogg.py
- xl/migrations/settings/flac_tempo.py
- xlgui/preferences/collection.py
Some metadata mappings are not like the standard.
Sources:
https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html
https://wiki.hydrogenaud.io/index.php?title=Tag_Mapping
https://docs.kde.org/trunk5/en/kid3/kid3/commands.html#frame-list
See also discussion at #682 
For flac and ogg there is new mapping and migration for bpm and comment.
> Migrate metadata mapping

- plugins/equalizer/__init__.py
As we are supporting Python >= 3.6, we can rely on this function being present in Python's standard library.
> chore: Deduplicate code from Python standard lib

- plugins/icecast/__init__.py
HTTP is not private and allows man-in-the-middle attacks. HTTPS provides some privacy and protects against simple man-in-the-middle attacks.
> chore: Use HTTPS for icecast access

- Makefile
Without this env variable it's impossible to run tests successfully in a non-english environment.
> Set LANGUAGE=C for 'make test' to get rid of localisation errors

- xl/collection.py
- xl/trax/track.py
- xl/trax/trackdb.py
Fixes #883
Reproduction:
* Add a folder with cover.png (or any other unsupported file) to the library
* Mark the folder as monitored
* Change the name of cover.png
After this cover.png is imported to the library.
With this pull request there will be a test if a file is supported.
Also the accidentally imported files will be removed.
> Don't add unsupported media files to library

- Makefile
In this PR I would like to disable fuzzy matching for msgmerge.
While generating po files for #877 I saw that `msgmerge` fuzzy matching wants to use the translation of `Disc metadata` as the translation of `Migrating metadata`, which would be wrong. This happens even with the current master
If using the `--no-fuzzy-matching` switch it won't happen.
Example without `--no-fuzzy-matching`
```
#: ../xlgui/preferences/collection.py:195
#, fuzzy
#| msgid "Disc metadata"
msgid "Migrating metadata"
msgstr "CD-Metadaten"
```
Example with `--no-fuzzy-matching`
```
#: ../xlgui/preferences/collection.py:195
msgid "Migrating metadata"
msgstr ""
```
> Disable fuzzy matching for msgmerge

- plugins/wikipedia/__init__.py
Currently the wikipedia plugin is not showing any web content, because the content retrieved by urllib needs to be decoded to string.
Additionally the enhancement from #875 is integrated.
> Wikipedia plugin: decode page content to string

- .github/workflows/ci.yml
- DEPS
Update tested distribution versions, reflecting [exaile/exaile-testimg!2](https://github.com/exaile/exaile-testimg2/pull/1).
Update dependencies based on the package version shipped by our oldest supported distribution, Ubuntu 20.04 (old LTS) with help of Ubuntu's package list https://packages.ubuntu.com/
> Update tested distribution versions and dependencies

- tests/xl/trax/test_search.py
- tests/xl/trax/test_track.py
- tests/xl/trax/test_util.py
See also: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
> chore: fix some pytest warnings

- plugins/daapclient/client.py
- plugins/keybinder/__init__.py
- xl/externals/gi_composites.py
- xl/player/gst/__init__.py
- xl/trax/track.py
- xlgui/guiutil.py
- xlgui/widgets/info.py
This code is no longer needed because support for the software versions it refers to has been removed.
> chore: Drop some outdated backward compatibility code

- plugins/audioscrobbler/__init__.py
- plugins/bookmarks/__init__.py
- plugins/daapclient/__init__.py
- plugins/shutdown/__init__.py
Fixes #901 by replacing the reference to track-properties menu item with slow-scan-collection menu item
> Fix gone track-properties menu item references

- xlgui/widgets/dialogs.py
With this the MultiTextEntryDialog widget is able to show text entries with preset value and an optional hint.
> Extend multitextentrydialog with values and hints

- plugins/shutdown/__init__.py
- plugins/shutdown/shutdown_preferences.py
- plugins/shutdown/shutdown_preferences.ui
This adds a plugin preference page to set the shutdown timeout and to activate the "Close Exaile after Playback" checkbox automatically each start of Exaile.
> Shutdown plugin - Add preferences for activation by default and timeout

- xl/collection.py
A bug was introduced in #885 by potentially adding tracks to `removals` twice if both conditions are true. This results in a KeyError when removal of the second track is attempted because the `location` has already been deleted from `self.tracks`:
File "./xl/trax/trackdb.py", line 369, in remove_tracks
self._deleted_keys.append(self.tracks[location]._key)
KeyError: 'file:///...'
> Don't remove tracks twice during scan.

- xl/player/track_fader.py
Seen while testing #940 
In case of playing a file that's not readable by mutagen the track length is unknown.
This causes the fader to stop immediately. 
Return None in this case instead diables the fader for this track.
> Track-Fader: Return None if track length is unknown

- xlgui/panel/collection.py
When using Custom Collection Orders plugin it happens that after disabling the plugin the last active order is out of range.
> Collection order show nothing if last active was out of range

- xl/plugins.py
- xlgui/preferences/plugin.py
1. Plugin reload fails 
Setting the entry in `sys.modules`to none does not remove the key from the dict (at least in Python 3.12
2. Plugin remove crashes Exaile
The confirmation dialog on removing an user installed plugin causes a SIGSEV
> Plugin reload fails and remove crashes

- xlgui/widgets/playback.py
I don't know if the issues can actually be triggered, but the existing code was definitely wrong.
1. `property` is a typo; should be `gproperty`.
2. In this code, KeyError is never raised; it will just write to a new key in `self.__values` (which is a normal dict):
```py
try:
self.__values[gproperty.name] = value
except KeyError:
...
```
> Fix marker props

- Makefile
Previously this depended on the po/LINGUAS file created by the `pot` target, potentially causing error on `make -j`.
This commit also changes the `locale` target to not depend on `desktop_files` because `locale` is only meant to build the .mo files.
As a bonus, this also results in the .desktop and appdata files now not being pointlessly created in the Windows CI build. We make the installation of these files optional in the `make install` step.
> Fix .desktop & appdata generation

- xl/main.py
- xl/plugins.py
GLib 2.84 integrates GIRepository (as `-3.0`), and that broke Exaile (even though the `-2.0` typelib & gir files still exist; I guess they're not usable anymore?).
There are a few ways we can fix this; in this commit I simply use a try-except, which seems the cleanest to me. The alternative is to import GLib then check `GLib.glib_version`, which I'd be fine with as well.
This commit also moves the `require_version` call from main.py to plugins.py, where the GIRepository import actually is.
Fixes: https://github.com/exaile/exaile/issues/962
> Support GIRepository-3.0

- xl/plugins.py
The old GIRepository API (exposed by PyGObject < 3.52.0) has a `Repository.get_default()` method to obtain global singleton object; this method was removed in the new API (exposed by PyGObject >= 3.52.0), which requires creation of separate `Repository` instances.
Properly handle both APIs, in order to fix plugin enumeration when PyGObject >= 3.52.0 is used; otherwise, trying to list plugins in Preferences dialog fails with "Could not load plugin info! Failed plugins: <list of all plugins>" message, which is caused by an `AttributeError` in `PluginsManager.is_potentially_broken()`.
> xl/plugins: fix plugin enumeration with PyGObject >= 3.52.0

- plugins/lyricsmania/__init__.py
This is essentially a reversion of #861.
I received [a report](https://github.com/NixOS/nixpkgs/issues/442879) that the lyricsmania plugin wasn't working and found that it wasn't working for me either. When I dug into it, I found that it was caused by a KeyError on the #video-musictory element, which I'm not seeing in the browser either.
While it's possible that this element still exists in some situations, it strikes me as more likely that the html has changed for good and I'm just the first to notice and report. I could move this all to a `try` block if we think it's necessary but I'm erring on the side of deletion unless someone disagrees.
Also removing the unreachable `return` earlier in the file.
> lyricsmania: Fix unexisting element lookup
