exaile/exaile

- plugins/cd/PLUGININFO
This is according to docs at https://exaile.readthedocs.org/en/latest/user/deps.html
Fixes issue #27
> Make clear that only one of HAL/Udisks/Udisks2 is needed

- doc/dev/release.rst
I removed the references to launchpad. Since I have no access to the UI the description is a bit vague.
I removed all references to creating a new branch for new versions since it seems like this is not done anymore anyway.
> Update release.rst/Translations to Weblate

- xl/nls.py
@sjohannes or @mathbr can you sanity check this for me? Fixes #54.
Before applying this fix, if you ran exaile on linux via `sudo make install` and `LANG="de_DE.utf8" exaile`, the locale files wouldn't get loaded properly. However, after applying this fix it seems to work for me.
> Set the locale path dependent on where we were installed

- xlgui/properties.py
A few changes were done if comparing to the orignal properties.
The most significative one being the format of the string indicating the
last time the file was modified, not it is presented in the preferred
representation for the current locale.
> xlgui/properties: gtk3-ize the properties.py

- plugins/console/__init__.py
- plugins/console/console_window.ui
I added a glade .ui file for this plugin and ported it to Gtk 3.x removing deprecated GtkVBox and GtkHBox.
> [gi] Port "simple console" plugin to Gtk 3.x, add .ui file

- plugins/bpm/bpm.ui
Improves 94b3629d789f4c211860da8d2266c3fb92aa3d1d
> BPM: remove deprecated GtkAlignment

- plugins/contextinfo/PLUGININFO
- plugins/contextinfo/__init__.py
- plugins/contextinfo/inspector.py
- plugins/daapclient/PLUGININFO
- plugins/daapserver/PLUGININFO
- plugins/daapserver/spydaap/parser/avi.py
- plugins/daapserver/spydaap/parser/exaile.py
- plugins/daapserver/spydaap/parser/mp3.py
- plugins/daapserver/spydaap/parser/vorbis.py
- plugins/daapserver/spydaap/server.py
- plugins/ipod/PLUGININFO
- plugins/minimode/PLUGININFO
- plugins/osd/PLUGININFO
- plugins/winmmkeys/PLUGININFO
Improves plugin dependencies, makes Lyrics Viewer and Wikipedia run at the same time and fixes daapserver imports so daapserver can start
> [gi] Plugins: some minor fixes

- data/ui/preferences/plugin.ui
- data/ui/preferences/preferences_dialog.ui
See https://github.com/exaile/exaile/issues/117#issuecomment-114544119 for details.
> [gi] Make preferences window resize to fit content

- data/ui/preferences/plugin.ui
I accidentially closed #106, this is the change from there.
> reduce size of description, reduce UI elements (again)

- plugins/contextinfo/PLUGININFO
- plugins/mainmenubutton/PLUGININFO
This is a redo of #133 where I messed git up.
> Update some PLUGININFO files (redone)

- xlgui/widgets/playlist.py
@sjohannes can you take a look at this? Seems to work great for those pesky really large playlists, not sure if I missed an important race condition anywhere...
> Add a 'loading' indicator when loading large playlists

- Makefile
Two "minor" fixes to get plugins working and banish import errors.
> Install and import fixes

- INSTALL
- Makefile
- tools/generate-launcher
for amazoncovers plugin to work.  I forgot about this one, and I promise to start testing gi branch now...  really...
> Fixes for Makefile

- data/ui/preferences/appearance.ui
- data/ui/preferences/collection.ui
- data/ui/preferences/cover.ui
- data/ui/preferences/playback.ui
- data/ui/preferences/playlists.ui
- data/ui/preferences/plugin.ui
This GtkWindow is not used and thus can be removed.
> Preferences UI files: remove GtkWindow

- plugins/jamendo/__init__.py
- xlgui/cover.py
- xlgui/devices.py
This will make use of system-specific file separators.
> Use xdg.get_data_path correctly

- xl/formatter.py
- xlgui/widgets/playlist_columns.py
@SaiyanRiku try this out and let me know if it does what you want.
> Add year column

- data/ui/about_dialog.ui
- data/ui/collection_manager.ui
- data/ui/device_manager.ui
- xlgui/collection.py
- xlgui/devices.py
- xlgui/widgets/dialogs.py
Add GtkTemplate to About dialog, Collection manager and Device manager.
> Use gtktemplate

- data/ui/preferences/widgets/selection_list_preference.ui
- plugins/daapclient/__init__.py
- plugins/equalizer/equalizer.ui
- plugins/minimode/__init__.py
- plugins/minimode/controls.py
- plugins/notifyosd/__init__.py
- plugins/osd/__init__.py
- plugins/wikipedia/__init__.py
- xlgui/cover.py
- xlgui/guiutil.py
- xlgui/preferences/widgets.py
- xlgui/widgets/info.py
Some minor fixes to the gi branch, mostly related to Gtk API breaks from Gtk2 to Gtk3. Fixes some plugins and warnings.
> Some minor fixes to the gi branch, mostly Gtk2 to Gtk3 API breaks

- plugins/notify/__init__.py
Fix an issue preventing notify plugin to display notifications due to an API change
> Fix notify plugin

- plugins/currentsong/PLUGININFO
- plugins/desktopcover/desktopcover_preferences.py
- plugins/notify/__init__.py
- plugins/osd/osd_preferences.py
- plugins/wikipedia/__init__.py
- xlgui/preferences/plugin.py
Just some minor fixes. Mostly to get less warnings.
> Minor fixes

- DEPS
I forgot to change this in my commit b85904e (#183)
> Reflect unbundling pylast

- INSTALL
> Add uninstall information on Linux/*nix systems.

- xlgui/widgets/playback.py
This change adds a feature also known from e.g. VLC media player:
When scrolling on SeekProgressBar, progress is being changed adding/removing some seconds.
There is no fixed reason why I chose 5% and 0.5%, you may change that.
I am unable to test the "smooth scroll" part, but the rest is working fine. No problems when not playing songs. Press your scroll wheel left/right to "scroll" left/right.
> SeekProgressBar: enable seek on scroll

- xlgui/properties.py
see https://github.com/mypaint/mypaint/issues/236
and https://github.com/mypaint/mypaint/commit/d12f42585d04758d90163789553b05f2866a75e7
This should fix #217, fix confirmed working by @strahlc. Please someone have a look over it anyway, especially on a non-Fedora/non-Gtk+ 3.18 system.
> Fix traceback when saving cover to metadata

- xl/trax/track.py
Fix #225 as discussed in #239.
> Remove "Unknown" labels from unset/empty tags.

- po/de.po
> fixed typo

- xl/trax/search.py
I have used the unidecode library to add the ability to ignore diacritics while searching. If the unidecode library is present, then typing in something like "motley crue" or "mötley crüe" will both match "Mötley Crüe". This was done by converting both the `search_string` and the tag values into ascii text when a search was conducted. If the user does not have the unidecode library, then the default behavior is restored where diacritics are not ignored during search. I have tested this on my system and it works for searching when unicode and non-unicode strings are utilized for searching tracks.
> This fixes exaile/exaile#176: Ignore diacritics for search

- xl/trax/search.py
This fix allows for normalization of strings while ignoring any unicode characters that cannot be converted into ascii.
> Fix exaile/exaile #270 (Non-Latin search always matches every track)

- plugins/grouptagger/gt_import.py
- xl/common.py
- xlgui/progress.py
This is an idea for simplfying the progress monitor stuff. It's not particularly well tested yet, but I think it's sound. I had started migrating the collection progress monitor to it, but got distracted so it's not in here. Would be good to integrate this with my gio library, perhaps?
> Simplify progress thread usage and make it threadsafe

- po/sv.po
Signed-off-by: Kristoffer Grundström <hamnisdude@gmail.com>
> New translation and adjustments

- plugins/lyricwiki/__init__.py
the slicing of the last 7 lines does not seem to be useful anymore, it cuts of the last lines of the lyrics now
I couldn't find lyrics where the cut off makes sense ... I guess there was a change on lyrics wiki that no longer requires this
> Fix lyrics from lyrics wiki cut off

- exaile.py
- plugins/grouptagger/gt_widgets.py
- plugins/minimode/__init__.py
- xlgui/widgets/dialogs.py
- xlgui/widgets/filter.py
- xlgui/widgets/rating.py
Some minor fixes over the tree
> Minor fixes for warnings

- xlgui/widgets/dialogs.py
Because of a GObject introspection bug (GNOME bug #616044, #708297, #746111).
This patch works around the issue by implementing the async copy behavior in a separate thread.
How to test / how I tested this patch:
1. open any playlist
2. right-click on playlist tab, select "Export Files"
3. select a directory:
* one without the files
* one with the files already present
* one without write permissions (e.g. `/usr/`)
4. If file already exists, try each button
> Implement async file copy (work around #198)

- plugins/cd/__init__.py
- plugins/cd/cdprefs.py
- plugins/cd/importer.py
- xl/transcoder.py
Fixes #320 and a few other issues related to the CD plugin/panel, making it work. Still room for improvement, but enough to ship in Exaile 4.0 pre-release for now in my opinion.
flac quality levels: There is a related GStreamer bug: https://bugzilla.gnome.org/show_bug.cgi?id=776413
tl;dr: GStreamer says, flac has quality levels 0…9 but it really has just level 0…8 so setting level 9 will always fail.
> Fix cd plugin/panel and transcoder

- plugins/abrepeat/__init__.py
- plugins/bpm/__init__.py
- plugins/grouptagger/gt_widgets.py
- plugins/jamendo/__init__.py
- plugins/librivox/__init__.py
- plugins/mainmenubutton/__init__.py
- plugins/minimode/controls.py
- plugins/moodbar/__init__.py
- plugins/osd/__init__.py
- plugins/podcasts/__init__.py
- plugins/previewdevice/__init__.py
- xlgui/cover.py
- xlgui/main.py
- xlgui/panel/collection.py
- xlgui/panel/files.py
- xlgui/panel/flatplaylist.py
- xlgui/panel/playlists.py
- xlgui/panel/radio.py
- xlgui/tray.py
- xlgui/widgets/common.py
- xlgui/widgets/notebook.py
- xlgui/widgets/playback.py
- xlgui/widgets/playlist.py
Magic numbers are bad, replace them by library defined constants.
> Button events: Use Gdk.BUTTON_* instead of magic numbers

- plugins/bpm/__init__.py
- plugins/bpm/msg.ui
Autodetect only. Often the gstreamer plugin is off by a power of 2, so this is useful.. of course, it's also sometimes way off.
> bpm: Add dialog to allow selecting a harmonic of the BPM

- .github/ISSUE_TEMPLATE.md
Let me know if this sounds good, or if it needs adjustment.
> Add github issue template to guide new bug reports

- xlgui/menu.py
- xlgui/widgets/playlist.py
Fixes #361 Some menu entries have invalid icons
> Fix some icon names

- xlgui/widgets/common.py
Fixes #351 
@sjohannes: Can you please test this change?
> Fix bug: Unable to reload plugin in debug mode

- data/ui/shortcuts_dialog.ui
- plugins/audioscrobbler/__init__.py
- plugins/minimode/__init__.py
- xlgui/accelerators.py
- xlgui/menu.py
- xlgui/playlist_container.py
- xlgui/widgets/dialogs.py
- xlgui/widgets/menu.py
- xlgui/widgets/menuitems.py
* Menu items can pull its callback/label data from an accelerator instead of typing it twice
* Adds a dialog showing all existing shortcuts
> Enhance accelerators

- xlgui/widgets/notebook.py
Left/right tab labels should:
* Not expand vertically.
* Have a larger minimum width.
See: https://github.com/exaile/exaile/issues/319
> xlgui/notebook: Fix appearance of left/right tracklist tab labels.

- xl/trax/track.py
> Revert "Fix #247: 0 gets sorted as the largest playcount value"

- plugins/abrepeat/__init__.py
- plugins/bpm/__init__.py
- plugins/grouptagger/gt_widgets.py
- plugins/jamendo/__init__.py
- plugins/librivox/__init__.py
- plugins/podcasts/__init__.py
- xlgui/cover.py
- xlgui/main.py
- xlgui/panel/collection.py
- xlgui/panel/files.py
- xlgui/panel/flatplaylist.py
- xlgui/panel/playlists.py
- xlgui/panel/radio.py
- xlgui/tray.py
- xlgui/widgets/common.py
- xlgui/widgets/notebook.py
- xlgui/widgets/playback.py
- xlgui/widgets/playlist.py
According to the docs on `Gdk.Event.triggers_context_menu()`, it should be used
in favor of comparing `event.button` to `Gdk.Button.SECONDARY`.
> Code style: Use Gdk.Event.triggers_context_menu()

- xlgui/widgets/common.py
This commit fixes a race condition causing a use-after-free. When dragging files,
1. the drag operation causes `on_drag_begin()` to be called with a `Gdk.DragContext` as `context`.
2. `_on_drag_begin()` is called async, because of `@common.threaded`.
3. `_set_drag_cover()` is being called on the main thread through `GLib.idle_add()`
4. At this time, the `context` object might be invalid, e.g. because the drag operation has finished already.
With this change, `_set_drag_cover()` will abort if the drag has already ended.
Fixes #424.
Fixes #67.
I'm waiting for confirmation in #424 before merging this commit.
> DragTreeView: fix use-after-free crash setting covers on dragged files (#424)

- xl/playlist.py
> Fix for issue #79 'Previous track' fails when playing in shuffle mode.

- plugins/daapclient/__init__.py
- plugins/daapserver/server.py
- plugins/daapserver/spydaap/server.py
A few changes only affecting the daapserver plugin.
> Plugin spydaap: Sync with upstream and minor fixes

- xl/metadata/_base.py
> xl/metadata: Return raw data also for non-mutagen types

- .travis.yml
Reflect changes made in https://github.com/exaile/exaile-testimg/pull/1
> Travis: Update Fedora 25 to Fedora 26

- plugins/daapclient/client.py
Last steps to make it comply with pyflakes rules
> Plugin daapclient: Remove unused variables

- doc/conf.py
- doc/mocks.py
- plugins/daapclient/client.py
- plugins/dist_plugin.py
- plugins/grouptagger/gt_export.py
- plugins/grouptagger/gt_mass.py
- plugins/jamendo/jamapi.py
- plugins/lyricwiki/__init__.py
- plugins/mpris2/__init__.py
- plugins/mpris2/mprisobject.py
- plugins/previewdevice/__init__.py
- tests/xl/trax/test_migration.py
- tools/db_explorer.py
- xl/metadata/tags.py
- xl/migrations/database/to_bsddb.py
- xlgui/__init__.py
- xlgui/main.py
- xlgui/menu.py
- xlgui/panel/lyrics.py
- xlgui/widgets/menu.py
- xlgui/widgets/smart_playlist_editor.py
With these changes applied, exaile code conforms to most of the PEP8 rules, so we can use pychecker in #449.
> Code style: A few improvements

- .travis.yml
- Makefile
This will allow us to find more coding bugs prior to committing code to the repository.
> Travis: Also build all of Exaile's code

- doc/dev/plugin_guide.rst
- doc/xl/trax.rst
- plugins/audioscrobbler/__init__.py
- plugins/bpm/__init__.py
- plugins/cd/__init__.py
- plugins/cd/_cdguipanel.py
- plugins/jamendo/__init__.py
- plugins/librivox/__init__.py
- plugins/minimode/controls.py
- plugins/podcasts/__init__.py
- xl/collection.py
- xl/lyrics.py
- xl/player/gst/gst_utils.py
- xl/player/player.py
- xl/playlist.py
- xl/trax/track.py
- xl/trax/trackdb.py
- xlgui/cover.py
- xlgui/main.py
- xlgui/panel/collection.py
- xlgui/panel/lyrics.py
- xlgui/panel/playlists.py
- xlgui/widgets/info.py
- xlgui/widgets/playlist.py
* Fixes #334
* Helps with #437
> Batch track_tags_changed events

- xl/playlist.py
- xl/trax/util.py
- xlgui/main.py
- xlgui/widgets/smart_playlist_editor.py
- Underlying implementation can sort by multiple tags, but not implemented by dialog
- Fixes #292
> Provide option to sort SmartPlaylists by a particular tag

- plugins/daapserver/PLUGININFO
As per https://pypi.python.org/pypi/spydaap and http://www.e6h.org/about.html
> "Spydaap" and comma

- plugins/icecast/__init__.py
> Fix menu to Icecast radio

- xl/covers.py
> Force the cover search when get_cover_data fails

- xl/main.py
- xlgui/__init__.py
Moves xlgui.mainloop function to inside passing self.quit to be called on exit
> Handling keyboard interruption to kill graciously

- xl/lyrics.py
Closes the database (shelve.BsdDbShelf) on quit application callback
> Fix to #442

- plugins/awn/__init__.py
- plugins/bookmarks/__init__.py
- plugins/desktopcover/__init__.py
- plugins/icecast/__init__.py
- plugins/jamendo/__init__.py
- plugins/notify/__init__.py
- xl/common.py
- xl/covers.py
- xl/trax/util.py
- xlgui/cover.py
- xlgui/guiutil.py
- xlgui/icons.py
- xlgui/panel/collection.py
- xlgui/panel/files.py
- xlgui/panel/flatplaylist.py
- xlgui/panel/playlists.py
- xlgui/panel/radio.py
- xlgui/widgets/common.py
Patch with some improvements for DragTreeView
- Fix of many mouse button selection issues (https://github.com/exaile/exaile/commit/6088681ed43a44beec65752733c2269e2d6a17ec)
- Menus are more tight to DragTreeView(https://github.com/exaile/exaile/pull/474/commits/eea7c8afaacb40891487b11315933fd2aae2f308)
- Use drag cover icon (https://github.com/exaile/exaile/commit/44d8219b64ba05084147ffd689e9f635e530018c)
> DragTreeView Improvements

- xlgui/widgets/playlist.py
> Good Fixes

- xl/playlist.py
- xlgui/widgets/smart_playlist_editor.py
- Useful for users that aren't familiar with regexes
Any objections to this silly addition? I'm willing to accept suggestions for a different search string instead of `!c=` and `c=`...  :)
> smart playlists: add 'contains word' operation

- xlgui/widgets/playlist.py
This commit implements the behavior from issue #495. When pressing
enter key or double clicking on the track (assuming selection does
not change):
- if track is paused, it will continue
- if track is playing, it will restart from the beginning
The behavior of space key remains unchanged (i.e., it always toggles
pause, unless selection has changed), although its handling has
been moved to on_key_press_event() handler where we prevent it
from causing the 'row-activated' signal to be emitted.
> Playlist: restart currently-playing track on activation (enter, double-click)

- xlgui/widgets/playlist.py
One of the functions I miss in exaile is the ability to sort the playlist by multiple colums, for example first by artist name and then by song title. Currently, sorting seems to be done only by the last-selected column, even though the track sorting functions appear to already support sorting by multiple fields.
This PR attemps to address this by implementing tracking of the sort column changes, and sorting the playlist using the obtained list of columns. This way, the last selected column is applied first, then the one that was selected before it, and so on. 
Note that the change of sort order applies to all columns and not just the last-selected one, as applying different sort orders on different colums would require larger changes across the codebase...
> Playlist widget: implement sorting across multiple columns

- xl/player/gst/sink.py
- xl/player/gst/sink_windows.py
I know, we want to do a 4.0 release, but this gets rid of a lot of nasty code! And as an added bonus, users can try out the WASAPI sinks if they're suffering from #76
> Use GstDeviceMonitor for all the devices!

- tools/installer/exaile.spec
Had to hack at pyinstaller to make this work, but I think the results are worth it. The Windows installer is ~47MB down from ~60MB. Also, a friend of mine was complaining about an issue related to an x264 dll error message in the rc0 release. This should address that.
Here's the list of (primary) DLLs excluded when building in my Windows environment:
```
Excluding gst_plugins/libgstwebrtc.dll
Excluding gst_plugins/libgstdvdsub.dll
Excluding gst_plugins/libgstopenal.dll
Excluding gst_plugins/libgstresindvd.dll
Excluding gst_plugins/libgstx265.dll
Excluding gst_plugins/libgstopenglmixers.dll
Excluding gst_plugins/libgstmxf.dll
Excluding gst_plugins/libgstvideorate.dll
Excluding gst_plugins/libgstopencv.dll
Excluding gst_plugins/libgstvideotestsrc.dll
Excluding libgstvideo-1.0-0.dll …
```
> Use pyinstaller analysis hook to exclude gst plugins we don't want

- plugins/minimode/controls.py
- xlgui/widgets/playlist.py
This PR provides fixes for Issues #528, #529, and #530.
> Mini mode fixes

- plugins/lastfmcovers/__init__.py
So to avoid last.fm cover fetching fail due to the fact that
last.fm default XML response turns out to be malformed for ElementTree
fixes #545
> lastfmcovers: request last.fm API responses in JSON format

- xl/metadata/_base.py
> metadata: lock computation of reverse mappings

- plugins/equalizer/__init__.py
> Equalizer: Save presets correctly

- plugins/daapclient/__init__.py
- plugins/daapclient/client.py
- xl/metadata/tags.py
- xl/trax/track.py
- xlgui/panel/collection.py
- xlgui/properties.py
- xlgui/widgets/playlist_columns.py
This PR implements improved support for Album Artist based library, as outlined in #575.
Changes:
* addition of "Album Artist" views to Collection pane
* always display Album Artist field in Track properties dialog
* added "Album artist" column to playlist
* DAAP client: retrieve album artist information from the server
> Album artist support

- xlgui/widgets/notebook.py
> xlgui/widgets/notebook.py: Work around bold font in context menu

- .travis.yml
This is a draft because it is blocked by exaile/exaile-testimg#9.
> Travis: Update to match docker image versions

- .travis.yml
Reverts exaile/exaile#615 as the depending travis build is not ready yet.
> Revert "Travis: Update to match docker image versions"

- .travis.yml
Retry because I merged #615 too fast.
> Travis: Update to match docker image versions (2nd try)

- xlgui/widgets/playlist.py
- xlgui/widgets/playlist_columns.py
* Extract to EditableColumn
* Write on edit
* Update edited value immediately instead of waiting for the cache to catch up
* Makes a difference on large playlists
* Make many columns editable
> Editable column updates

- xlgui/widgets/playlist.py
- xlgui/widgets/playlist_columns.py
Also incorporates @sjohannes rename tag on F2 because it seems cool too.
* Fixes #633
> Tracklist edit fix double click

- xlgui/panel/playlists.py
I barely understand all this dnd stuff, but these are some low-hanging fruits that I found.
> panel/playlists: Fix some dnd stuff.

- plugins/ipconsole/ipython_view.py
This PR attempts to fix #694 by first back-porting the upstream fixes for ipython_view.py, and then applying some additional fixes for issues that were discovered during testing.
> Fixes for ipconsole plugin

- xl/formatter.py
Fedora 33 comes with python 3.9, which reorganized its `string.Template` implementation. 
It removed the private `string._TemplateMetaclass` class, which our `_ParameterTemplateMetaclass` in `xl.formatter` inherits from. However, it turns out that our `_ParameterTemplateMetaclass` and `ParameterTemplate` fully re-implement all functionality that is used from them, so the least invasive fix for now is to simply turn those classes into stand-alone ones, independent of the `string.Template` implementation.
> xl/formatter: fix for python 3.9 compatibility

- xlgui/widgets/dialogs.py
Fixes: https://github.com/exaile/exaile/issues/745
> xlgui/widgets/dialogs: Remember last playlist export directory

- plugins/quickbuttons/PLUGININFO
- plugins/quickbuttons/__init__.py
- plugins/quickbuttons/qb_prefs.py
- plugins/quickbuttons/qb_prefs.ui
New Plugin to add quickbuttons like explained in #746
This time without changing all the lang files.
> Quick Buttons

- plugins/inhibitsuspend/__init__.py
I took the opportunity to pull out dbus-specific functionality into
DbusSuspendAdapter. Once Wayland's idle inhibition protocol is
stabilized it should be possible to adapt most wayland compositors with
a comparable WaylandAdapter. See
<https://wayland.app/protocols/idle-inhibit-unstable-v1>.
> inhibitsuspend: Support sway

- xl/logger_setup.py
> Don't write empty log files

- plugins/previewdevice/__init__.py
- xlgui/main.py
> Window title does not change after resuming from pause #779

- plugins/quickbuttons/PLUGININFO
- plugins/quickbuttons/__init__.py
- plugins/quickbuttons/qb_prefs.py
- plugins/quickbuttons/qb_prefs.ui
Replaces #776 
Second try to rebase failed. I'm looking for a good introduction....
Sorry.
> Quickbuttons add audio sink selection

- data/ui/preferences/appearance.ui
- plugins/quickbuttons/__init__.py
- xlgui/main.py
- xlgui/preferences/appearance.py
- xlgui/widgets/info.py
Fixes: https://github.com/exaile/exaile/issues/616
> Hide status bar or parts of it

- plugins/helloworld/__init__.py
- plugins/previewdevice/__init__.py
- xl/plugins.py
- xl/settings.py
- xlgui/preferences/plugin.py
see https://github.com/exaile/exaile/issues/777
> Plugin Previewdevice cannot be activated after deactivation #777

- xl/player/gst/engine.py
Fixes: https://github.com/exaile/exaile/issues/801
> Reset playbin after reconfiguring output device

- xlgui/widgets/menu.py
- xlgui/widgets/playlist.py
- xlgui/widgets/playlist_columns.py
Sort playlist columns menu alphabetical
Fixes: https://github.com/exaile/exaile/issues/322
> Add playlist columns next to the clicked column

- Makefile
- data/exaile.appdata.xml
- data/exaile.desktop
- plugins/Makefile
Changes necessary to create a debian package according to mentors.debian.org
The package in Debian Mentors: https://mentors.debian.net/package/exaile/
> Debian packaging

- data/ui/preferences/plugin.ui
- xl/main.py
- xl/plugins.py
- xl/xdg.py
- xlgui/__init__.py
- xlgui/preferences/plugin.py
Fixes: https://github.com/exaile/exaile/issues/788
> Plugin Installation and Removing

- xl/main.py
- xlgui/playlist_container.py
- xlgui/widgets/playlist.py
* won't start with an empty queue
* won't select the last played song in a playlist with more than 500 tracks
> If restore_play_state is active

- xl/main.py
> Hide window immediately if starting minimized

- DEPS
- plugins/cd/PLUGININFO
- plugins/cd/__init__.py
- plugins/cd/_cdguipanel.py
- plugins/cd/cdprefs.py
- plugins/cd/cdprefs_pane.ui
- plugins/cd/discid_parser.py
- plugins/cd/linux_cd_parser.py
- plugins/cd/musicbrainzngs_parser.py
- plugins/musicbrainzcovers/__init__.py
- tools/installer/requirements.txt
This just a rebase and python syntax and formatting update of #652.
> Replace cddb by libdiscid

- Makefile
for the icon files. This is required for https://github.com/flathub/flathub/pull/3731.
> Adhere to FreeDesktop specifications

- data/exaile.appdata.xml.in
required for https://github.com/flathub/flathub/pull/3731
> Enhance FreeDesktop.org AppStream metadata

- xl/player/gst/engine.py
Fixes https://github.com/exaile/exaile/issues/841
> Fix remote streams not triggering track events

- plugins/lyricsmania/__init__.py
For me this seems to be a bug in lxml. See https://bugs.launchpad.net/lxml/+bug/2009356
> Lyricsmania doesn't display first line of lyrics (fixes #860)

- plugins/bpm/__init__.py
- plugins/bpm/bpm_prefs.py
- plugins/bpm/bpm_prefs.ui
> Disable confirmation after manually setting bpm count

- plugins/streamripper/__init__.py
* use custom useragent
* handle new version of playback_track_start
Thanks to @eri-trabiccolo
> Fix streamripper plugin

- data/ui/preferences/collection.ui
- data/ui/widgets/info_dialog.ui
- xl/main.py
- xlgui/widgets/dialogs.py
There is a new dialog that is shown on first run after installing Exaile 4.1.3.
The aim is to inform users about the new function for rating, bpm and tempo tags.
Any ideas for improvements and optimizations are very welcome.
> Update info dialog

- xl/metadata/__init__.py
- xl/metadata/wav.py
> Add error handling if file not readable

- plugins/customcollectionorders/__init__.py
- plugins/customcollectionorders/cco_pane.ui
- plugins/customcollectionorders/cco_prefs.py
* Add icon button for editing
* Strip tags in levels and display
* Changing some labels
> Custom collection order - improvements

- plugins/audioscrobbler/_scrobbler.py
- plugins/bpm/bpmdetect.py
- plugins/cd/discid_parser.py
- plugins/cd/linux_cd_parser.py
- plugins/cd/musicbrainzngs_parser.py
- plugins/helloworld/__init__.py
- plugins/inhibitsuspend/__init__.py
- xl/common.py
- xl/nls.py
- xl/player/__init__.py
- xl/providers.py
- xl/settings.py
- xl/unicode.py
- xl/xldbus.py
- xlgui/icons.py
- xlgui/widgets/common.py
- xlgui/widgets/menuitems.py
Probably should pin black to a specific version, but... eh
> Update black formatting

- tests/xl/test_FormatConverter.py
- xl/playlist.py
- xlgui/widgets/dialogs.py
* use paths instead of uris for local files
* fixes #932
> playlist export
